os: linux
language: php
dist: focal

php:
    - '7.4'
    - '8.0'

matrix:
  include:
    - php: '7.2'
      dist: bionic
    - php: '7.3'
      dist: bionic

before_install:
  - phpenv config-add tests/travis/php$TRAVIS_PHP_VERSION.ini

install:
  - export TRAVIS_PHP_VERSION; sh tests/travis/install-script.sh

script:
  - sh tests/travis/run-test.sh
